version: "3.3"
services:
  back:
    volumes:
      - "./log:/app/log"
    build:
      context: ../
      dockerfile: deploy/dev.dockerfile
    ports:
      - 5000:5000
    depends_on: 
      - pgb
    env_file:
     - my_env.env
    environment:
      PGPORT: 6432
      TZ: Europe/Moscow
      PGHOST: pgb
  pgb:
    image: pgbouncer/pgbouncer
    logging:
      driver: none #disabled spam logs
    depends_on:
      - db
    env_file:
     - my_env.env
    environment:
      TZ: UTC-3:00
      DATABASES_HOST: db
      DATABASES_PORT: 5432
    ports: 
      - 6432:6432
  db:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
     - my_env.env
    environment:
      TZ: Europe/Moscow
      PGDATA: /pg-data
    volumes:
      - ./pg-data:/pg-data
  nginx:
    image: nginx:alpine
    logging:
      driver: none #disabled spam logs
    depends_on: 
      - back
    ports:
      - 80:80
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    environment:
      TZ: Europe/Moscow
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./redisdata:/data
    ports:
      - 6379:6379