version: '3'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - .mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - .elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.2.1-1
    volumes:
      - .graylog/data/journal:/usr/share/graylog/data/journal
    env_file:
     - env_for_graylog.env
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: http://192.168.10.4:9000/api/
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
      - "514:514/udp"